# test_api.py
import requests

url = "http://127.0.0.1:8000/predict"

data = {
    "EntryPoint": 4096,
    "magic_number": 267,
    "bytes_on_last_page": 1024,
    "pages_in_file": 5,
    "relocations": 0,
    "size_of_header": 512,
    "min_extra_paragraphs": 0,
    "max_extra_paragraphs": 1,
    "init_ss_value": 4096,
    "init_sp_value": 8192,
    "init_ip_value": 4096,
    "init_cs_value": 4096,
    "over_lay_number": 0,
    "oem_identifier": 0,
    "address_of_ne_header": 1024,
    "SizeOfCode": 2048,
    "SizeOfInitializedData": 1024,
    "SizeOfUninitializedData": 0,
    "AddressOfEntryPoint": 4096,
    "BaseOfCode": 2048,
    "BaseOfData": 0,
    "ImageBase": 4194304,
    "SectionAlignment": 4096,
    "FileAlignment": 512,
    "OperatingSystemVersion": 5,
    "ImageVersion": 0,
    "SizeOfImage": 8192,
    "SizeOfHeaders": 512,
    "Checksum": 0,
    "SizeofStackReserve": 8192,
    "SizeofStackCommit": 4096,
    "SizeofHeapCommit": 4096,
    "SizeofHeapReserve": 8192,
    "LoaderFlags": 0,
    "text_VirtualSize": 1024,
    "text_VirtualAddress": 4096,
    "text_SizeOfRawData": 1024,
    "text_PointerToRawData": 512,
    "text_PointerToRelocations": 0,
    "text_PointerToLineNumbers": 0,
    "rdata_VirtualSize": 1024,
    "rdata_VirtualAddress": 5120,
    "rdata_SizeOfRawData": 1024,
    "rdata_PointerToRawData": 1536,
    "rdata_PointerToRelocations": 0,
    "rdata_PointerToLineNumbers": 0,
    "registry_read": 1,
    "registry_write": 0,
    "registry_delete": 0,
    "network_threats": 0,
    "network_dns": 1,
    "network_http": 1,
    "network_connections": 0,
    "processes_monitored": 5,
    "files_text": 10,
    "files_unknown": 0,
    "dlls_calls": 15,
    "apis": 25,
    "encryption_score": 7.0,
    "system_modification_score": 5.0
}

response = requests.post(url, json=data)
print(response.json())